### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by blaasvaer** [hillerstorm/wordfeud-api.js#1]
Hi,
Cool of you to create something like this. But how do I actually use it? I can't seem to be able to call any methods on the returned object.

Could you please provide basic usage syntax, to get started?

**Comment by hillerstorm** [comment]
Hi,

I haven't done anything with this for a few years :)
(except from updating the syntax 6 months ago)

This is a basic example which logs you in and gets all active games:

``` javascript
var Api = require('wordfeud-api');
var api = new Api();
api.login('USERNAME/EMAIL', 'PASSWORD', function(err, result) {
    if (err) return console.log(err);
    api.getGames(result.sessionId, function(err, games) {
        if (err) return console.log(err);
        console.log(games);
    });
});
```

What you get back from login is an object with a session id that you need for every consecutive call to any api method and a user object with id/username/email.
https://github.com/hillerstorm/wordfeud-api.js/blob/master/api.js#L382

I don't really remember why I wrote the code the way I did but all the methods without an underscore in front are "public" and usable :P

**Comment by hillerstorm** [comment]
Oh and a "move" is an array of arrays where each sub-array looks like this:
`[x, y, 'k', false]`

'k' being the letter to place and the last item should be `true` if the tile is a wildcard

or something... :D

This is all sniffed by playing the actual game with my phone hooked up to my computer so there's no official api :)

**Comment by blaasvaer** [comment]
Hi,

Thanks a lot. I'll look into it, and see if I can make it work.

Thanks again.
